// Registry of games shown on the hub. Add a line here when adding a game.
window.GAMES = [
  { id: 'snakeio', name: 'Snake.io', emoji: '🐍', color: '#30d158', desc: 'Eat, grow, cut them off' },
  { id: 'flappy', name: 'Flappy Dot', emoji: '🐤', color: '#ffd60a', desc: 'Tap to fly through gaps' },
  { id: '2048', name: '2048', emoji: '🔢', color: '#ff9f0a', desc: 'Swipe to merge tiles' },
  { id: 'stack', name: 'Stack', emoji: '🧱', color: '#bf5af2', desc: 'Tap to build a tower' },
  { id: 'tictactoe', name: 'Tic-Tac-Toe', emoji: '⭕', color: '#0a84ff', desc: 'Beat the watch' },
  { id: 'whack', name: 'Whack-a-Mole', emoji: '🐹', color: '#ac8e68', desc: '30 seconds of bonking' },
  { id: 'simon', name: 'Simon', emoji: '🔴', color: '#ff453a', desc: 'Repeat the pattern' },
  { id: 'pong', name: 'Pong', emoji: '🏓', color: '#64d2ff', desc: 'First to 7 vs the watch' },
  { id: 'breakout', name: 'Breakout', emoji: '🟪', color: '#5e5ce6', desc: 'Smash every brick' },
  { id: 'snake', name: 'Snake', emoji: '🍎', color: '#34c759', desc: 'Classic grid snake' },
  { id: 'mines', name: 'Minesweeper', emoji: '💣', color: '#8e8e93', desc: 'Clear the field fast', unit: 's' },
  { id: 'memory', name: 'Memory Match', emoji: '🃏', color: '#bf5af2', desc: 'Find all 8 pairs', unit: ' moves' },
  { id: 'reaction', name: 'Reaction', emoji: '⚡', color: '#ffd60a', desc: 'How fast are you?', unit: ' ms' },
  { id: 'dodge', name: 'Asteroid Dodge', emoji: '☄️', color: '#ff9f0a', desc: 'Fly, dodge, grab stars' },
  { id: 'math', name: 'Math Blitz', emoji: '🧮', color: '#0a84ff', desc: 'Quick-fire arithmetic' },
  { id: 'tiles', name: 'Piano Tiles', emoji: '🎹', color: '#e5e5ea', desc: 'Tap the black tiles' },
  { id: 'blobio', name: 'Blob.io', emoji: '🟢', color: '#30d158', desc: 'Eat or be eaten' },
  { id: 'dino', name: 'Dino Run', emoji: '🦖', color: '#34c759', desc: 'Tap to jump cacti' },
  { id: 'blocks', name: 'Blocks', emoji: '🟦', color: '#0a84ff', desc: 'Stack and clear lines' },
  { id: 'knife', name: 'Knife Hit', emoji: '🔪', color: '#a0703c', desc: 'Stick knives in the log' },
  { id: 'colorswitch', name: 'Color Switch', emoji: '🎨', color: '#ff375f', desc: 'Pass through your color' },
  { id: 'invaders', name: 'Invaders', emoji: '👾', color: '#bf5af2', desc: 'Defend against the swarm' },
  { id: 'fruit', name: 'Fruit Slice', emoji: '🍉', color: '#ff453a', desc: 'Swipe to slice, dodge bombs' },
  { id: 'connect4', name: 'Connect Four', emoji: '🔴', color: '#ffd60a', desc: 'Four in a row vs the watch' },
  { id: 'lightsout', name: 'Lights Out', emoji: '💡', color: '#ffd60a', desc: 'Switch every light off' },
  { id: 'fifteen', name: '15 Puzzle', emoji: '🧩', color: '#ff9f0a', desc: 'Slide tiles into order', unit: ' moves' },
  { id: 'orbit', name: 'Orbit', emoji: '🪐', color: '#5e5ce6', desc: 'Tap to reverse, grab gems' },
  { id: 'blackjack', name: 'Blackjack', emoji: '♠️', color: '#1f8f3a', desc: 'Beat the dealer to 21', unit: ' chips' },
  { id: 'hilo', name: 'Higher or Lower', emoji: '🎴', color: '#bf5af2', desc: 'Guess the next card' },
  { id: 'balloons', name: 'Balloon Pop', emoji: '🎈', color: '#ff375f', desc: 'Pop them before they escape' },
];
