// Registry of games shown on the hub. Add a line here when adding a game.
window.GAMES = [
  { id: 'snakeio', name: 'Snake.io', emoji: '🐍', color: '#30d158', desc: 'Eat, grow, cut them off' },
  { id: 'buggy', name: 'Beach Buggy', emoji: '🏖️', color: '#ff9f0a', desc: 'Kart racing with ❓ power-ups — Crown steers' },
  { id: 'flappy', name: 'Flappy Dot', emoji: '🐤', color: '#ffd60a', desc: 'Tap to fly through gaps' },
  { id: '2048', name: '2048', emoji: '🔢', color: '#ff9f0a', desc: 'Swipe to merge tiles' },
  { id: 'stack', name: 'Stack', emoji: '🧱', color: '#bf5af2', desc: 'Tap to build a tower' },
  { id: 'tictactoe', name: 'Tic-Tac-Toe', emoji: '⭕', color: '#0a84ff', desc: 'Beat the watch' },
  { id: 'whack', name: 'Whack-a-Mole', emoji: '🐹', color: '#ac8e68', desc: '30 seconds of bonking' },
  { id: 'simon', name: 'Simon', emoji: '🔴', color: '#ff453a', desc: 'Repeat the pattern' },
  { id: 'pong', name: 'Pong', emoji: '🏓', color: '#64d2ff', desc: 'First to 7 vs the watch' },
  { id: 'breakout', name: 'Breakout', emoji: '🟪', color: '#5e5ce6', desc: 'Smash every brick' },
  { id: 'snake', name: 'Snake', emoji: '🍎', color: '#34c759', desc: 'Classic grid snake' },
  { id: 'mines', name: 'Minesweeper', emoji: '💣', color: '#8e8e93', desc: 'Clear the field fast', unit: 's' },
  { id: 'memory', name: 'Memory Match', emoji: '🃏', color: '#bf5af2', desc: 'Find all 8 pairs', unit: ' moves' },
  { id: 'reaction', name: 'Reaction', emoji: '⚡', color: '#ffd60a', desc: 'How fast are you?', unit: ' ms' },
  { id: 'dodge', name: 'Asteroid Dodge', emoji: '☄️', color: '#ff9f0a', desc: 'Fly, dodge, grab stars' },
  { id: 'math', name: 'Math Blitz', emoji: '🧮', color: '#0a84ff', desc: 'Quick-fire arithmetic' },
  { id: 'tiles', name: 'Piano Tiles', emoji: '🎹', color: '#e5e5ea', desc: 'Tap the black tiles' },
  { id: 'blobio', name: 'Blob.io', emoji: '🟢', color: '#30d158', desc: 'Eat or be eaten' },
  { id: 'dino', name: 'Dino Run', emoji: '🦖', color: '#34c759', desc: 'Tap to jump cacti' },
  { id: 'blocks', name: 'Blocks', emoji: '🟦', color: '#0a84ff', desc: 'Stack and clear lines' },
  { id: 'knife', name: 'Knife Hit', emoji: '🔪', color: '#a0703c', desc: 'Stick knives in the log' },
  { id: 'colorswitch', name: 'Color Switch', emoji: '🎨', color: '#ff375f', desc: 'Pass through your color' },
  { id: 'invaders', name: 'Invaders', emoji: '👾', color: '#bf5af2', desc: 'Defend against the swarm' },
  { id: 'fruit', name: 'Fruit Slice', emoji: '🍉', color: '#ff453a', desc: 'Swipe to slice, dodge bombs' },
  { id: 'connect4', name: 'Connect Four', emoji: '🔴', color: '#ffd60a', desc: 'Four in a row vs the watch' },
  { id: 'lightsout', name: 'Lights Out', emoji: '💡', color: '#ffd60a', desc: 'Switch every light off' },
  { id: 'fifteen', name: '15 Puzzle', emoji: '🧩', color: '#ff9f0a', desc: 'Slide tiles into order', unit: ' moves' },
  { id: 'orbit', name: 'Orbit', emoji: '🪐', color: '#5e5ce6', desc: 'Tap to reverse, grab gems' },
  { id: 'blackjack', name: 'Blackjack', emoji: '♠️', color: '#1f8f3a', desc: 'Beat the dealer to 21', unit: ' chips' },
  { id: 'hilo', name: 'Higher or Lower', emoji: '🎴', color: '#bf5af2', desc: 'Guess the next card' },
  { id: 'balloons', name: 'Balloon Pop', emoji: '🎈', color: '#ff375f', desc: 'Pop them before they escape' },
  { id: 'numbers', name: 'Number Rush', emoji: '🔢', color: '#64d2ff', desc: 'Tap 1–16 in order', unit: 's' },
  { id: 'stop', name: 'Perfect Stop', emoji: '⏱️', color: '#30d158', desc: 'Stop the needle in the zone' },
  { id: 'cave', name: 'Cave Flyer', emoji: '🦇', color: '#248a3d', desc: 'Hold to rise through the cave' },
  { id: 'hop', name: 'Hop', emoji: '🐔', color: '#48a848', desc: 'Cross roads and rivers' },
  { id: 'maze', name: 'Maze', emoji: '🌀', color: '#0a84ff', desc: 'Roll to the exit' },
  { id: 'hanoi', name: 'Tower of Hanoi', emoji: '🗼', color: '#ff9f0a', desc: 'Move the tower, one disc at a time' },
  { id: 'eightball', name: 'Magic 8 Ball', emoji: '🎱', color: '#5e5ce6', desc: 'Ask it anything' },
  { id: 'rps', name: 'Rock Paper Scissors', emoji: '✌️', color: '#ff9f0a', desc: 'Outguess the watch' },
  { id: 'golf', name: 'Mini Golf', emoji: '⛳️', color: '#2f8f3f', desc: '6 holes, drag to putt', unit: ' strokes' },
  { id: 'jumper', name: 'Jumper', emoji: '🐸', color: '#30d158', desc: 'Bounce up — crown steers' },
  { id: 'stroop', name: 'Color Clash', emoji: '🌈', color: '#bf5af2', desc: 'Ink color, not the word' },
  { id: 'sudoku', name: 'Mini Sudoku', emoji: '🧠', color: '#64d2ff', desc: '6×6 number puzzle', unit: 's' },
  { id: 'hoops', name: 'Hoops', emoji: '🏀', color: '#ff8a1a', desc: 'Flick to sink shots' },
  { id: 'plinko', name: 'Plinko', emoji: '🔻', color: '#ff375f', desc: 'Drop balls, chase 10×' },
  { id: 'racer', name: 'Racer', emoji: '🏎️', color: '#ff453a', desc: 'Crown steers through traffic' },
  { id: 'hangman', name: 'Word Guess', emoji: '⛄', color: '#64d2ff', desc: 'Guess the word, save the snowman' },
  { id: 'airhockey', name: 'Air Hockey', emoji: '🏒', color: '#64d2ff', desc: 'First to 5 vs the watch' },
  { id: 'slots', name: 'Slots', emoji: '🎰', color: '#c9302c', desc: 'Spin — the Crown pulls the lever', unit: ' credits' },
  { id: 'chimp', name: 'Chimp Test', emoji: '🐵', color: '#ac8e68', desc: 'Remember hidden numbers' },
  { id: 'scramble', name: 'Word Scramble', emoji: '🔤', color: '#ffd60a', desc: 'Unscramble against the clock' },
  { id: 'darts', name: 'Darts', emoji: '🎯', color: '#e0302a', desc: 'Time your throws' },
  { id: 'bowling', name: 'Bowling', emoji: '🎳', color: '#d9a066', desc: 'Swipe to bowl, curve to hook' },
  { id: 'reversi', name: 'Reversi', emoji: '⚫', color: '#1f7a3a', desc: 'Flip discs vs the watch' },
  { id: 'dots', name: 'Dots & Boxes', emoji: '🔲', color: '#30d158', desc: 'Claim more boxes than the watch' },
  { id: 'pig', name: 'Pig Dice', emoji: '🐷', color: '#ff9fb4', desc: 'Push your luck to 50' },
  { id: 'sokoban', name: 'Box Push', emoji: '📦', color: '#8e5a3c', desc: 'Sokoban: 6 puzzle levels' },
  { id: 'battleship', name: 'Battleship', emoji: '🚢', color: '#0f4c81', desc: 'Sink the watch’s fleet' },
  { id: 'nim', name: 'Nim', emoji: '🕯️', color: '#ff9f0a', desc: 'Take the last candle' },
  { id: 'timber', name: 'Lumberjack', emoji: '🪓', color: '#8b5a2b', desc: 'Chop fast, dodge branches' },
  { id: 'asteroids', name: 'Asteroids', emoji: '🌑', color: '#8e8e93', desc: 'Crown aims, auto-fire' },
  { id: 'tunnel', name: 'Tunnel', emoji: '🕳️', color: '#bf5af2', desc: 'Crown spins you through gaps' },
  { id: 'mancala', name: 'Mancala', emoji: '🪨', color: '#8b5a2b', desc: 'Sow stones, capture, outscore' },
  { id: 'flood', name: 'Flood It', emoji: '🌊', color: '#0a84ff', desc: 'Fill the board in 22 moves', unit: ' moves' },
  { id: 'codebreaker', name: 'Code Breaker', emoji: '🔐', color: '#5e5ce6', desc: 'Crack the colour code', unit: ' tries' },
  { id: 'catch', name: 'Catch', emoji: '🧺', color: '#457b9d', desc: 'Crown moves the basket' },
  { id: 'cookie', name: 'Cookie Clicker', emoji: '🍪', color: '#c48a50', desc: 'Tap or spin the Crown to bake' },
  { id: 'bubbles', name: 'Bubble Shooter', emoji: '🫧', color: '#0a84ff', desc: 'Match 3 — Crown aims' },
  { id: 'pet', name: 'Pocket Pet', emoji: '🐣', color: '#ffd60a', desc: 'Raise a pet that grows over days' },
  { id: 'lander', name: 'Lunar Lander', emoji: '🌕', color: '#8e8e93', desc: 'Crown tilts, hold to thrust' },
  { id: 'artillery', name: 'Artillery', emoji: '💣', color: '#5b7f3a', desc: 'Crown aims — first to 3 hits' },
  { id: 'safe', name: 'Safe Cracker', emoji: '💰', color: '#6e6e73', desc: 'Spin the Crown to find the code' },
  { id: 'nonogram', name: 'Nonogram', emoji: '🖼️', color: '#0a84ff', desc: 'Fill the grid from number clues' },
  { id: 'golfsolitaire', name: 'Golf Solitaire', emoji: '🂡', color: '#1f8f3a', desc: 'Clear cards one rank up or down', unit: ' left' },
  { id: 'five', name: 'Five', emoji: '🟩', color: '#30d158', desc: 'Guess the 5-letter word' },
  { id: 'pipes', name: 'Pipes', emoji: '🚰', color: '#64d2ff', desc: 'Rotate tiles to connect the water' },
  { id: 'penalty', name: 'Penalty Kick', emoji: '⚽️', color: '#2e8b3a', desc: 'Swipe to beat the keeper' },
  { id: 'homerun', name: 'Home Run Derby', emoji: '⚾️', color: '#2e7d32', desc: 'Time your swing for homers' },
  { id: 'duckhunt', name: 'Duck Hunt', emoji: '🦆', color: '#5ac8fa', desc: 'Tap the ducks, 3 shots each' },
  { id: 'checkers', name: 'Checkers', emoji: '👑', color: '#8b5a2b', desc: 'Jump and king vs the watch' },
  { id: 'tenseconds', name: 'Stop at 10', emoji: '⏲️', color: '#ff9f0a', desc: 'Stop the hidden timer at 10.00', unit: 's off' },
  { id: 'fishing', name: 'Fishing', emoji: '🎣', color: '#2b8fd6', desc: 'Crown reels in the catch' },
  { id: 'chase', name: 'Ghost Chase', emoji: '👻', color: '#ffd60a', desc: 'Eat the dots, dodge ghosts' },
  { id: 'gems', name: 'Gem Swap', emoji: '💎', color: '#bf5af2', desc: 'Match 3 gems, chain combos' },
  { id: 'cycles', name: 'Light Cycles', emoji: '🏍️', color: '#64d2ff', desc: 'Box in the other riders' },
  { id: 'papertoss', name: 'Paper Toss', emoji: '🗑️', color: '#8b6b4a', desc: 'Flick it in, beat the wind' },
  { id: 'capitals', name: 'Capitals Quiz', emoji: '🌍', color: '#0a84ff', desc: 'Name the capital city' },
  { id: 'bubblewrap', name: 'Bubble Wrap', emoji: '🫧', color: '#64d2ff', desc: 'Pop, pop, pop — forever' },
  { id: 'tugofwar', name: 'Tug of War', emoji: '💪', color: '#4caf50', desc: 'Out-tap the robots' },
  { id: 'rhythm', name: 'Rhythm Tap', emoji: '🎵', color: '#ff375f', desc: 'Tap the lanes on the beat' },
  { id: 'dash', name: 'Dash', emoji: '🟨', color: '#ffd60a', desc: 'Jump spikes, land on blocks' },
  { id: 'helix', name: 'Helix Drop', emoji: '🗼', color: '#ff9f0a', desc: 'Crown spins the tower' },
  { id: 'timestables', name: 'Times Tables', emoji: '✖️', color: '#30d158', desc: 'Multiply fast for 60 seconds' },
  { id: 'dicepoker', name: 'Dice Poker', emoji: '🎲', color: '#c9302c', desc: 'Roll, hold, make a hand' },
  { id: 'oddone', name: 'Odd One Out', emoji: '🔍', color: '#ffd60a', desc: 'Spot the different emoji' },
  { id: 'ballsort', name: 'Ball Sort', emoji: '🧪', color: '#bf5af2', desc: 'Sort the coloured balls' },
  { id: 'snakeblocks', name: 'Snake vs Blocks', emoji: '🔢', color: '#30d158', desc: 'Crown steers through numbered blocks' },
  { id: 'digitspan', name: 'Digit Span', emoji: '🧮', color: '#64d2ff', desc: 'How many digits can you hold?' },
  { id: 'pinball', name: 'Pinball', emoji: '🪩', color: '#bf5af2', desc: 'Flip, bump, score' },
  { id: 'skeeball', name: 'Skee-Ball', emoji: '🎟️', color: '#a0703c', desc: 'Roll for the 100 holes' },
  { id: 'slalom', name: 'Ski Slalom', emoji: '⛷️', color: '#0a84ff', desc: 'Crown carves through the gates' },
  { id: 'twistit', name: 'Twist It!', emoji: '⌚', color: '#ff9f0a', desc: 'Tap, swipe, hold or twist the Crown!' },
  { id: 'pegs', name: 'Peg Solitaire', emoji: '📍', color: '#c48a50', desc: 'Jump pegs, leave just one' },
  { id: 'gomoku', name: 'Five in a Row', emoji: '⚫', color: '#d9a95b', desc: 'Gomoku vs the watch' },
  { id: 'wordsearch', name: 'Word Search', emoji: '🔤', color: '#ff9f0a', desc: 'Find 5 hidden words' },
  { id: 'burger', name: 'Burger Stack', emoji: '🍔', color: '#e0a050', desc: 'Catch the order in sequence' },
  { id: 'jetpack', name: 'Jetpack', emoji: '🧑‍🚀', color: '#ffd60a', desc: 'Hold to fly, dodge zappers' },
  { id: 'memorygrid', name: 'Memory Grid', emoji: '🟦', color: '#0a84ff', desc: 'Remember the lit squares' },
  { id: 'dropmerge', name: 'Drop Merge', emoji: '🔢', color: '#5e5ce6', desc: 'Drop numbers, merge doubles' },
  { id: 'keepyuppy', name: 'Keepy Uppy', emoji: '⚽️', color: '#87ceeb', desc: 'Tap to keep the ball up' },
  { id: 'bricksballs', name: 'Bricks & Balls', emoji: '⚪', color: '#5e5ce6', desc: 'Aim a stream of balls at bricks' },
  { id: 'flags', name: 'Flag Quiz', emoji: '🏳️', color: '#ff453a', desc: 'Name the country from its flag' },
  { id: 'squash', name: 'Squash', emoji: '🎾', color: '#d9c3a0', desc: 'Solo rally — Crown moves the racket' },
  { id: 'tiletrio', name: 'Tile Trio', emoji: '🍓', color: '#8b5a2b', desc: 'Match 3 tiles, keep the tray clear' },
  { id: 'bulletdodge', name: 'Bullet Dodge', emoji: '💠', color: '#ff375f', desc: 'Survive the bullet patterns' },
  { id: 'dragrace', name: 'Drag Race', emoji: '🏁', color: '#30d158', desc: 'Launch on green, shift perfectly' },
  { id: 'archery', name: 'Archery', emoji: '🏹', color: '#5aa04a', desc: 'Crown aims, hold to draw' },
  { id: 'pancake', name: 'Pancake Flip', emoji: '🥞', color: '#f2c66d', desc: 'Flip and serve perfect pancakes' },
  { id: 'walljump', name: 'Wall Jump', emoji: '🥷', color: '#4a3f6b', desc: 'Leap between walls, dodge spikes' },
  { id: 'iceslide', name: 'Ice Slide', emoji: '🐧', color: '#64d2ff', desc: 'Slide the penguin home' },
  { id: 'fruitmerge', name: 'Fruit Merge', emoji: '🍉', color: '#ff9f0a', desc: 'Merge fruit up to a watermelon' },
  { id: 'blockblast', name: 'Block Blast', emoji: '🟪', color: '#bf5af2', desc: 'Place blocks, clear rows and columns' },
  { id: 'holeio', name: 'Hole.io', emoji: '🕳️', color: '#30d158', desc: 'Swallow the city, beat 3 rival holes' },
  { id: 'paperio', name: 'Paper.io', emoji: '🟩', color: '#30d158', desc: 'Loop out and claim land vs 3 bots' },
  { id: 'survivor', name: 'Survivor', emoji: '🧙', color: '#30d158', desc: 'Auto-battle hordes, level up, survive 5 min' },
  { id: 'railrunner', name: 'Rail Runner', emoji: '🚆', color: '#ff453a', desc: '3D endless runner — swipe or Crown' },
  { id: 'hillracer', name: 'Hill Racer', emoji: '🚙', color: '#ff453a', desc: 'Physics hill climb — Crown is the gas pedal' },
  { id: 'pool', name: 'Pool', emoji: '🎱', color: '#1f8f4a', desc: 'Pot balls vs the watch' },
];

// Hub filters. A game can appear in one category; CROWN marks games playable with the Digital Crown.
window.CATEGORIES = {
  Arcade: ['snakeio', 'blobio', 'flappy', 'stack', 'dino', 'knife', 'colorswitch', 'invaders', 'fruit', 'dodge', 'cave', 'hop',
    'jumper', 'racer', 'asteroids', 'tunnel', 'catch', 'orbit', 'balloons', 'whack', 'breakout', 'pong', 'snake', 'airhockey', 'timber', 'tiles', 'bubbles', 'lander', 'artillery', 'buggy', 'duckhunt', 'chase', 'cycles', 'tugofwar', 'rhythm', 'dash', 'helix', 'snakeblocks', 'pinball', 'twistit', 'burger', 'jetpack', 'bricksballs', 'bulletdodge', 'walljump', 'holeio', 'paperio', 'survivor', 'railrunner', 'hillracer'],
  Puzzle: ['2048', 'blocks', 'mines', 'lightsout', 'fifteen', 'maze', 'hanoi', 'sudoku', 'sokoban', 'flood', 'codebreaker', 'nonogram', 'pipes', 'gems', 'ballsort', 'pegs', 'dropmerge', 'tiletrio', 'iceslide', 'fruitmerge', 'blockblast'],
  Brain: ['simon', 'memory', 'reaction', 'math', 'numbers', 'stop', 'stroop', 'chimp', 'scramble', 'hangman', 'safe', 'five', 'tenseconds', 'capitals', 'timestables', 'oddone', 'digitspan', 'wordsearch', 'memorygrid', 'flags'],
  Board: ['tictactoe', 'connect4', 'reversi', 'dots', 'mancala', 'battleship', 'nim', 'blackjack', 'hilo', 'pig', 'rps', 'golfsolitaire', 'checkers', 'dicepoker', 'gomoku'],
  Sports: ['golf', 'hoops', 'bowling', 'darts', 'penalty', 'homerun', 'papertoss', 'skeeball', 'slalom', 'keepyuppy', 'squash', 'dragrace', 'archery', 'pool'],
  Fun: ['eightball', 'slots', 'cookie', 'plinko', 'pet', 'fishing', 'bubblewrap', 'pancake'],
};
window.CROWN = ['pool', 'hillracer', 'railrunner', 'survivor', 'paperio', 'holeio', 'fruitmerge', 'archery', 'squash', 'bricksballs', 'burger', 'twistit', 'slalom', 'snakeblocks', 'helix', 'tugofwar', 'fishing', 'buggy', 'safe', 'artillery', 'lander', 'pet', 'bubbles', 'snakeio', 'blobio', 'blocks', 'invaders', 'jumper', 'racer', 'asteroids', 'tunnel', 'catch', 'cookie', 'eightball', 'slots'];
