// Registry of games shown on the hub. Add a line here when adding a game.
window.GAMES = [
  { id: 'snakeio', name: 'Snake.io', emoji: '🐍', color: '#30d158', desc: 'Eat, grow, cut them off' },
  { id: 'flappy', name: 'Flappy Dot', emoji: '🐤', color: '#ffd60a', desc: 'Tap to fly through gaps' },
  { id: '2048', name: '2048', emoji: '🔢', color: '#ff9f0a', desc: 'Swipe to merge tiles' },
  { id: 'stack', name: 'Stack', emoji: '🧱', color: '#bf5af2', desc: 'Tap to build a tower' },
  { id: 'tictactoe', name: 'Tic-Tac-Toe', emoji: '⭕', color: '#0a84ff', desc: 'Beat the watch' },
  { id: 'whack', name: 'Whack-a-Mole', emoji: '🐹', color: '#ac8e68', desc: '30 seconds of bonking' },
  { id: 'simon', name: 'Simon', emoji: '🔴', color: '#ff453a', desc: 'Repeat the pattern' },
  { id: 'pong', name: 'Pong', emoji: '🏓', color: '#64d2ff', desc: 'First to 7 vs the watch' },
  { id: 'breakout', name: 'Breakout', emoji: '🟪', color: '#5e5ce6', desc: 'Smash every brick' },
  { id: 'snake', name: 'Snake', emoji: '🍎', color: '#34c759', desc: 'Classic grid snake' },
  { id: 'mines', name: 'Minesweeper', emoji: '💣', color: '#8e8e93', desc: 'Clear the field fast', unit: 's' },
  { id: 'memory', name: 'Memory Match', emoji: '🃏', color: '#bf5af2', desc: 'Find all 8 pairs', unit: ' moves' },
  { id: 'reaction', name: 'Reaction', emoji: '⚡', color: '#ffd60a', desc: 'How fast are you?', unit: ' ms' },
  { id: 'dodge', name: 'Asteroid Dodge', emoji: '☄️', color: '#ff9f0a', desc: 'Fly, dodge, grab stars' },
  { id: 'math', name: 'Math Blitz', emoji: '🧮', color: '#0a84ff', desc: 'Quick-fire arithmetic' },
  { id: 'tiles', name: 'Piano Tiles', emoji: '🎹', color: '#e5e5ea', desc: 'Tap the black tiles' },
  { id: 'blobio', name: 'Blob.io', emoji: '🟢', color: '#30d158', desc: 'Eat or be eaten' },
  { id: 'dino', name: 'Dino Run', emoji: '🦖', color: '#34c759', desc: 'Tap to jump cacti' },
  { id: 'blocks', name: 'Blocks', emoji: '🟦', color: '#0a84ff', desc: 'Stack and clear lines' },
  { id: 'knife', name: 'Knife Hit', emoji: '🔪', color: '#a0703c', desc: 'Stick knives in the log' },
  { id: 'colorswitch', name: 'Color Switch', emoji: '🎨', color: '#ff375f', desc: 'Pass through your color' },
  { id: 'invaders', name: 'Invaders', emoji: '👾', color: '#bf5af2', desc: 'Defend against the swarm' },
  { id: 'fruit', name: 'Fruit Slice', emoji: '🍉', color: '#ff453a', desc: 'Swipe to slice, dodge bombs' },
  { id: 'connect4', name: 'Connect Four', emoji: '🔴', color: '#ffd60a', desc: 'Four in a row vs the watch' },
  { id: 'lightsout', name: 'Lights Out', emoji: '💡', color: '#ffd60a', desc: 'Switch every light off' },
  { id: 'fifteen', name: '15 Puzzle', emoji: '🧩', color: '#ff9f0a', desc: 'Slide tiles into order', unit: ' moves' },
  { id: 'orbit', name: 'Orbit', emoji: '🪐', color: '#5e5ce6', desc: 'Tap to reverse, grab gems' },
  { id: 'blackjack', name: 'Blackjack', emoji: '♠️', color: '#1f8f3a', desc: 'Beat the dealer to 21', unit: ' chips' },
  { id: 'hilo', name: 'Higher or Lower', emoji: '🎴', color: '#bf5af2', desc: 'Guess the next card' },
  { id: 'balloons', name: 'Balloon Pop', emoji: '🎈', color: '#ff375f', desc: 'Pop them before they escape' },
  { id: 'numbers', name: 'Number Rush', emoji: '🔢', color: '#64d2ff', desc: 'Tap 1–16 in order', unit: 's' },
  { id: 'stop', name: 'Perfect Stop', emoji: '⏱️', color: '#30d158', desc: 'Stop the needle in the zone' },
  { id: 'cave', name: 'Cave Flyer', emoji: '🦇', color: '#248a3d', desc: 'Hold to rise through the cave' },
  { id: 'hop', name: 'Hop', emoji: '🐔', color: '#48a848', desc: 'Cross roads and rivers' },
  { id: 'maze', name: 'Maze', emoji: '🌀', color: '#0a84ff', desc: 'Roll to the exit' },
  { id: 'hanoi', name: 'Tower of Hanoi', emoji: '🗼', color: '#ff9f0a', desc: 'Move the tower, one disc at a time' },
  { id: 'eightball', name: 'Magic 8 Ball', emoji: '🎱', color: '#5e5ce6', desc: 'Ask it anything' },
  { id: 'rps', name: 'Rock Paper Scissors', emoji: '✌️', color: '#ff9f0a', desc: 'Outguess the watch' },
  { id: 'golf', name: 'Mini Golf', emoji: '⛳️', color: '#2f8f3f', desc: '6 holes, drag to putt', unit: ' strokes' },
  { id: 'jumper', name: 'Jumper', emoji: '🐸', color: '#30d158', desc: 'Bounce up — crown steers' },
  { id: 'stroop', name: 'Color Clash', emoji: '🌈', color: '#bf5af2', desc: 'Ink color, not the word' },
  { id: 'sudoku', name: 'Mini Sudoku', emoji: '🧠', color: '#64d2ff', desc: '6×6 number puzzle', unit: 's' },
  { id: 'hoops', name: 'Hoops', emoji: '🏀', color: '#ff8a1a', desc: 'Flick to sink shots' },
  { id: 'plinko', name: 'Plinko', emoji: '🔻', color: '#ff375f', desc: 'Drop balls, chase 10×' },
  { id: 'racer', name: 'Racer', emoji: '🏎️', color: '#ff453a', desc: 'Crown steers through traffic' },
  { id: 'hangman', name: 'Word Guess', emoji: '⛄', color: '#64d2ff', desc: 'Guess the word, save the snowman' },
  { id: 'airhockey', name: 'Air Hockey', emoji: '🏒', color: '#64d2ff', desc: 'First to 5 vs the watch' },
  { id: 'slots', name: 'Slots', emoji: '🎰', color: '#c9302c', desc: 'Spin — the Crown pulls the lever', unit: ' credits' },
  { id: 'chimp', name: 'Chimp Test', emoji: '🐵', color: '#ac8e68', desc: 'Remember hidden numbers' },
  { id: 'scramble', name: 'Word Scramble', emoji: '🔤', color: '#ffd60a', desc: 'Unscramble against the clock' },
  { id: 'darts', name: 'Darts', emoji: '🎯', color: '#e0302a', desc: 'Time your throws' },
  { id: 'bowling', name: 'Bowling', emoji: '🎳', color: '#d9a066', desc: 'Swipe to bowl, curve to hook' },
  { id: 'reversi', name: 'Reversi', emoji: '⚫', color: '#1f7a3a', desc: 'Flip discs vs the watch' },
  { id: 'dots', name: 'Dots & Boxes', emoji: '🔲', color: '#30d158', desc: 'Claim more boxes than the watch' },
  { id: 'pig', name: 'Pig Dice', emoji: '🐷', color: '#ff9fb4', desc: 'Push your luck to 50' },
  { id: 'sokoban', name: 'Box Push', emoji: '📦', color: '#8e5a3c', desc: 'Sokoban: 6 puzzle levels' },
  { id: 'battleship', name: 'Battleship', emoji: '🚢', color: '#0f4c81', desc: 'Sink the watch’s fleet' },
  { id: 'nim', name: 'Nim', emoji: '🕯️', color: '#ff9f0a', desc: 'Take the last candle' },
  { id: 'timber', name: 'Lumberjack', emoji: '🪓', color: '#8b5a2b', desc: 'Chop fast, dodge branches' },
  { id: 'asteroids', name: 'Asteroids', emoji: '🌑', color: '#8e8e93', desc: 'Crown aims, auto-fire' },
  { id: 'tunnel', name: 'Tunnel', emoji: '🕳️', color: '#bf5af2', desc: 'Crown spins you through gaps' },
  { id: 'mancala', name: 'Mancala', emoji: '🪨', color: '#8b5a2b', desc: 'Sow stones, capture, outscore' },
  { id: 'flood', name: 'Flood It', emoji: '🌊', color: '#0a84ff', desc: 'Fill the board in 22 moves', unit: ' moves' },
  { id: 'codebreaker', name: 'Code Breaker', emoji: '🔐', color: '#5e5ce6', desc: 'Crack the colour code', unit: ' tries' },
  { id: 'catch', name: 'Catch', emoji: '🧺', color: '#457b9d', desc: 'Crown moves the basket' },
  { id: 'cookie', name: 'Cookie Clicker', emoji: '🍪', color: '#c48a50', desc: 'Tap or spin the Crown to bake' },
  { id: 'bubbles', name: 'Bubble Shooter', emoji: '🫧', color: '#0a84ff', desc: 'Match 3 — Crown aims' },
  { id: 'pet', name: 'Pocket Pet', emoji: '🐣', color: '#ffd60a', desc: 'Raise a pet that grows over days' },
  { id: 'lander', name: 'Lunar Lander', emoji: '🌕', color: '#8e8e93', desc: 'Crown tilts, hold to thrust' },
  { id: 'artillery', name: 'Artillery', emoji: '💣', color: '#5b7f3a', desc: 'Crown aims — first to 3 hits' },
  { id: 'safe', name: 'Safe Cracker', emoji: '💰', color: '#6e6e73', desc: 'Spin the Crown to find the code' },
];

// Hub filters. A game can appear in one category; CROWN marks games playable with the Digital Crown.
window.CATEGORIES = {
  Arcade: ['snakeio', 'blobio', 'flappy', 'stack', 'dino', 'knife', 'colorswitch', 'invaders', 'fruit', 'dodge', 'cave', 'hop',
    'jumper', 'racer', 'asteroids', 'tunnel', 'catch', 'orbit', 'balloons', 'whack', 'breakout', 'pong', 'snake', 'airhockey', 'timber', 'tiles', 'bubbles', 'lander', 'artillery'],
  Puzzle: ['2048', 'blocks', 'mines', 'lightsout', 'fifteen', 'maze', 'hanoi', 'sudoku', 'sokoban', 'flood', 'codebreaker'],
  Brain: ['simon', 'memory', 'reaction', 'math', 'numbers', 'stop', 'stroop', 'chimp', 'scramble', 'hangman', 'safe'],
  Board: ['tictactoe', 'connect4', 'reversi', 'dots', 'mancala', 'battleship', 'nim', 'blackjack', 'hilo', 'pig', 'rps'],
  Sports: ['golf', 'hoops', 'bowling', 'darts'],
  Fun: ['eightball', 'slots', 'cookie', 'plinko', 'pet'],
};
window.CROWN = ['safe', 'artillery', 'lander', 'pet', 'bubbles', 'snakeio', 'blobio', 'blocks', 'invaders', 'jumper', 'racer', 'asteroids', 'tunnel', 'catch', 'cookie', 'eightball', 'slots'];
